### ISSUE TITLE
failed to setup

### ISSUE THREAD

**Issue by briandye** [G-Two/homeassistant-subaru#113]
Hi there, things were working good for me up until recently. I show the below in my home assistant log. I have tried to uninstall and reinstall the integration. All the steps in authenticating, entering validation code and entering PIN work as expected.

`2024-02-05 22:33:25.096 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry myemail@domain.com for subaru
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 103, in async_setup_entry
    vehicles[vin] = await _get_vehicle_info(controller, vin)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 218, in _get_vehicle_info
    VEHICLE_HAS_POWER_WINDOWS: await controller.has_power_windows(vin),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/subarulink/controller.py", line 286, in has_power_windows
    await self.get_data(vin)
  File "/usr/local/lib/python3.11/site-packages/subarulink/controller.py", line 409, in get_data
    await self.fetch(vin)
  File "/usr/local/lib/python3.11/site-packages/subarulink/controller.py", line 569, in fetch
    result = await self._fetch_status(vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/subarulink/controller.py", line 1058, in _fetch_status
    status = self._parse_vehicle_status(js_resp, vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/subarulink/controller.py", line 1285, in _parse_vehicle_status
    status[sc.HEADING] = int(data.get(api.API_HEADING))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by briandye** [comment]
For some reason a reload of the Integration today and it’s working again.
