### ISSUE TITLE
HACS Failed to Setup My Subaru App

### ISSUE THREAD

**Issue by tweas** [G-Two/homeassistant-subaru#120]
I have been using this for quite some time now.  I just got the error "HACS Failed to Setup"  I did just update to 2024.5.2 in Docker mode.

Log entry from trying to reload:

Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 5:02:57 PM (1 occurrences)
Last logged: 5:02:57 PM

Error setting up entry {MyEmailAddressRedacted} for subaru
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 103, in async_setup_entry
    vehicles[vin] = await _get_vehicle_info(controller, vin)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 218, in _get_vehicle_info
    VEHICLE_HAS_POWER_WINDOWS: await controller.has_power_windows(vin),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 286, in has_power_windows
    await self.get_data(vin)
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 409, in get_data
    await self.fetch(vin)
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 569, in fetch
    result = await self._fetch_status(vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 1058, in _fetch_status
    status = self._parse_vehicle_status(js_resp, vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 1285, in _parse_vehicle_status
    status[sc.HEADING] = int(data.get(api.API_HEADING))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by G-Two** [comment]
It looks like an old bug that was fixed a few months ago. What version of this custom component are you using?

**Comment by tweas** [comment]
Weird, I was up to date.  I restored a system backup from 2 days ago and it is working again.  I was really thinking something with the 2024.5.2 update broke functionality.  But, all ticking along now.
