### ISSUE TITLE
Websocket error every few minutes

### ISSUE THREAD

**Issue by jharris4** [G-Two/homeassistant-subaru#122]
I just installed this integration, and it seems to be working fine, other than I keep getting an error message even when I'm not actually doing anything.

Here's the error I'm seeing in the logs:

```
2024-05-22 17:52:01.767 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546870360128] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 134, in _async_press_action
    await self.async_press()
  File "/config/custom_components/subaru/button.py", line 154, in async_press
    await self.coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 291, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/sensor.py", line 294, in extra_state_attributes
    PressureConverter.convert(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 78, in convert
    return cls.converter_factory(from_unit, to_unit)(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 89, in 
    return lambda val: (val / from_ratio) * to_ratio
                        ~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
2024-05-22 17:57:02.315 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/sensor.py", line 294, in extra_state_attributes
    PressureConverter.convert(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 78, in convert
    return cls.converter_factory(from_unit, to_unit)(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 89, in 
    return lambda val: (val / from_ratio) * to_ratio
                        ~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by jharris4** [comment]
I'm in Canada using Metric system, and a quick glance at the code seems to point at a bug specific to this case...

**Comment by G-Two** [comment]
Would you please attach your diagnostics output?

**Comment by jharris4** [comment]
Sure, here you go!

[subaru-7d740fd5e86943646274952f43ba30ee-JF2SKEPC4PH408272-0d0e149903e481014081797ee22cc0f6.json](https://github.com/G-Two/homeassistant-subaru/files/15425931/subaru-7d740fd5e86943646274952f43ba30ee-JF2SKEPC4PH408272-0d0e149903e481014081797ee22cc0f6.json)

Funny timing I was literally just looking at the issue because I finally have spare time to look at the source to see if I can debug further myself.

Please let me know if there's anything I can do to help debug. Thanks!

**Comment by G-Two** [comment]
I think I found the bug:

It looks like the Subaru API doesn't include a recommended tire pressure in your vehicle features. There's a check to see if the dict is populated with the data (should be length of 2, if the data is provided): https://github.com/G-Two/homeassistant-subaru/blob/8c975f8430eedf2234c4f47e885df42f1d4bb6da/custom_components/subaru/sensor.py#L276

But there's a subsequent else block that tries to get the value for a non-existent key and passes it along for conversion:
https://github.com/G-Two/homeassistant-subaru/blob/8c975f8430eedf2234c4f47e885df42f1d4bb6da/custom_components/subaru/sensor.py#L290

**Comment by jharris4** [comment]
Ah! I was just digging into the pressure unit conversion code, thinking it was something to do with that logic specifically.

Happy to test out any code changes if you think there's an easy fix.

**Comment by G-Two** [comment]
I published a prerelease version https://github.com/G-Two/homeassistant-subaru/releases/tag/v0.7.15dev0
It should show as available in HACS. Please give it a try and let me know if it fixes the issue.

**Comment by jharris4** [comment]
Awesome thanks, the error seems to be gone!

I am however seeing all 4 tires with pressure displayed as `0.0 hPa`, is this to be expected?

**Comment by G-Two** [comment]
Looking at your diagnostics output, it looks like there is no reported tire pressure right now. If you drive around for a few minutes and then turn off the vehicle, it should start reporting tire pressure.

Unfortunately, it looks like I may have broke other things with this prerelease, so I'll have to keep working on it later. Feel free to keep using this one, I'll make sure to keep the bug fix for your case in any subsequent release.

**Comment by jharris4** [comment]
Interesting, no tire data in history so far, but maybe it'll start showing up with this fix. I'll check after I use the car tomorrow morning.

Thanks again, and sorry to hear that the fix has caused other issues.

**Comment by G-Two** [comment]
Apparently "dev" version numbers break things, so I switched to "rc": https://github.com/G-Two/homeassistant-subaru/releases/tag/v0.7.15rc0

This should fix the issue without breaking everything else.

**Comment by jharris4** [comment]
I used the car this morning, but all tire pressures are still being reported as 0.

**Comment by jharris4** [comment]
To test the fix I just copied over the new `sensor.py` into my `custom_components` then a restart of HA.

I've done a proper update to rc0 now, and there's the latest diagnostics output:

[subaru-7d740fd5e86943646274952f43ba30ee-JF2SKEPC4PH408272-0d0e149903e481014081797ee22cc0f6 (2).json](https://github.com/G-Two/homeassistant-subaru/files/15441025/subaru-7d740fd5e86943646274952f43ba30ee-JF2SKEPC4PH408272-0d0e149903e481014081797ee22cc0f6.2.json)

**Comment by stboch** [comment]
@jharris4 does your tire pressure show up in the my Subaru app?

**Comment by jharris4** [comment]
I got an email notification that someone mentioned me and asked if the tire pressure was showing up in the MySubaru app.

The answer to that question is no, I wasn't able to see the tire pressure displayed anywhere in the MySubaru app. Maybe it shows up for people in the US but not Canada?

I also wonder if there's some TPMS feature that my Forester is missing. Do people who have tire pressure displaying in the app have anything related to that in the `vehicles_features` list perhaps?

**Comment by G-Two** [comment]
Do you have the ability to view your individual tire pressures inside your vehicle? If so, it's strange that they wouldn't send that information through.

There is a `TMPS_MIL` listed in my features (2019 Crosstrek PHEV):

```json
      "vehicle_features": [
        "ABS_MIL",
        "AHBL_MIL",
        "ATF_MIL",
        "AWD_MIL",
        "BSD",
        "BSDRCT_MIL",
        "CEL_MIL",
        "EBD_MIL",
        "EOL_MIL",
        "EPAS_MIL",
        "EPB_MIL",
        "ESS_MIL",
        "EYESIGHT",
        "HEVCM_MIL",
        "HEV_MIL",
        "NAV_TOMTOM",
        "OPL_MIL",
        "PHEV",
        "RAB_MIL",
        "RCC",
        "REARBRK",
        "RPOIA",
        "SRS_MIL",
        "TEL_MIL",
        "TIF_36",
        "TIR_35",
        "TPMS_MIL",
        "VDC_MIL",
        "WASH_MIL",
        "g2"
      ],
```

**Comment by jharris4** [comment]
Ok, so it sounds like the vehicle_features could be used to filter out certain things like the tire pressure then!

Unless Subaru provide details around that I could see it being a lot of work to reverse engineer...

Funny that it's spelled `tyre` in the code, when they only support countries that spell it `tire`. I wonder where the MySubaru dev team are based.

**Comment by jharris4** [comment]
Ahh TIL, here's a [reddit thread](https://www.reddit.com/r/SubaruForester/comments/yz2qci/canadian_forester_owners_we_got_shortchanged_on/) with Canadians griping about how Subaru commonly sell vehicles without TPMS in Canada.

Kinda makes sense in a way that they don't offer it in Canada. Here in Quebec where I live by law we have to put on snow tires every winter and apparently it costs more to change tires when TPMS enabled, and also TPMS get affected by large temperature fluctuations like we get.

**Comment by G-Two** [comment]
Wow, I had no idea Subaru sold cars without TPMS. I updated the latest pre-release to check for TPMS before adding the tire pressure sensors. So this should fix the original bug you reported, as well as eliminate the tire pressure entities from appearing in the first place for unsupported vehicles.

https://github.com/G-Two/homeassistant-subaru/releases/tag/v0.7.15rc1

**Comment by jharris4** [comment]
Nice, thanks for looking into this so thoroughly!

One last question: Is there any support for locating the vehicle? I can do that through the MySubaru app, and I’d love to setup some automations for when the car leaves/returns etc…

**Comment by G-Two** [comment]
Yes, there should be a device tracker entity in HA that shows your vehicle's last reported location.

**Comment by jharris4** [comment]
Oh wow, that's sweet, thanks! I didn't think to look for it because it wasn't on the overview card.

**Comment by G-Two** [comment]
Fixed: https://github.com/G-Two/homeassistant-subaru/releases/tag/v0.7.15
