### ISSUE TITLE
Error prevented the integration from working at all until it was reloaded.

### ISSUE THREAD

**Issue by jharris4** [G-Two/homeassistant-subaru#125]
I noticed today that none of the Subaru functionality was working properly. All the entities related to it said unavailable.

I was only able to fix it by reloading the integration manually.

I checked the logs, and the following error was reported:

```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: June 10, 2024 at 10:29:22 PM (1 occurrences)
Last logged: June 10, 2024 at 10:29:22 PM

Error setting up entry <redacted_email>@gmail.com for subaru
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 102, in async_setup_entry
    vehicles[vin] = await _get_vehicle_info(controller, vin)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 210, in _get_vehicle_info
    VEHICLE_HAS_LOCK_STATUS: await controller.has_lock_status(vin),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 334, in has_lock_status
    await self.get_data(vin)
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 448, in get_data
    await self.fetch(vin)
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 608, in fetch
    result = await self._fetch_status(vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 1120, in _fetch_status
    raise err
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 1113, in _fetch_status
    await self._locate(vin)
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 1155, in _locate
    js_resp = await self._remote_query(vin, api.API_LOCATE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/subarulink/controller.py", line 1022, in _remote_query
    raise SubaruException("Remote query failed. Response: %s " % js_resp)
subarulink.exceptions.SubaruException
```

**Comment by tweas** [comment]
How did you reload it manually?  Download the files again or run the configuration again?

**Comment by jharris4** [comment]
@tweas you can reload the integration through the UI:

Settings -> Devices & services -> Integrations tab -> Subaru (HACS)

Once you navigate to that page, there should be a small `...` option on the right next to 'CONFIGURE' under "Integration entries".

If you click the `...` there should be a `Reload` option at the top of the resulting popup menu. Hope that helps!

**Comment by tweas** [comment]
Yes, aware of the how's.  I was just asking which option you meant when you said reload.  Not everyone uses the actual terminolgy from the app when commenting.  So, wanted to confirm if "reloading" was the actual "Reload" option.  OR, did you have to download and effectively reinstall the custom configuration in order to resolve.

In any case, the issue I was having was that mysubaru itself was down when I ran the latest core update making me think the update had broken the integration.

**Comment by jharris4** [comment]
I just noticed all my Subaru sensors have been unavailable for the past 2 days. Reloading the integration fixed it. Looks like my original issue isn’t fixed even with version 0.7.22

**Comment by G-Two** [comment]
Is the same error reported in the logs?

**Comment by jharris4** [comment]
Looks like a slightly different error:

```
This error originated from a custom integration.

Logger: custom_components.subaru
Source: helpers/update_coordinator.py:504
Integration: Subaru (HACS) (documentation, issues)
First occurred: May 17, 2026 at 12:51:56 AM (4 occurrences)
Last logged: May 20, 2026 at 12:08:22 AM

Error fetching subaru_data data: Remote query failed. Response: {'success': False, 'errorCode': None, 'dataName': 'remoteServiceStatus', 'data': {'serviceRequestId': None, 'success': False, 'cancelled': False, 'remoteServiceType': None, 'remoteServiceState': None, 'subState': None, 'errorCode': None, 'result': None, 'updateTime': None, 'vin': None, 'errorDescription': None}}
Error fetching subaru_data data: aiohttp.ClientConnectionError
Error fetching subaru_data data: HTTP 502: <html>
 <head><title>502 Bad Gateway</title></head>
 <body>
 <center><h1>502 Bad Gateway</h1></center>
 <hr><center></center>
 </body>
 </html>
 RequestInfo(url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/validateSession.json'), method='GET', headers=<CIMultiDictProxy('Host': 'mobileapi.ca.prod.subarucs.com', 'User-Agent': 'HomeAssistant/2026.5.2 aiohttp/3.13.5 Python/3.14', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Cookie': 'JSESSIONID=E86BDB5F25EE44AFA9A09B5EEA60CFC6; X-Oracle-BMC-LBS-Route=4f65eea550dddceedeb77fa2e2997443fe398a6327da03a11a2ff120e313e9b656c62fd8a7c42ae88e33cc6f5c2623d8c0e515bc08fb3341c8323933')>, real_url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/validateSession.json'))
```

**Comment by jharris4** [comment]
Just noticed my car went unavailable again last night and didn’t come back.

```
This error originated from a custom integration.

Logger: custom_components.subaru
Source: helpers/update_coordinator.py:504
Integration: Subaru (HACS) (documentation, issues)
First occurred: May 25, 2026 at 8:56:39 PM (5 occurrences)
Last logged: May 26, 2026 at 11:59:36 PM

Error fetching subaru_data data: aiohttp.ClientConnectionError
Error fetching subaru_data data: HTTP 504: <html>
 <head><title>504 Gateway Time-out</title></head>
 <body>
 <center><h1>504 Gateway Time-out</h1></center>
 <hr><center></center>
 </body>
 </html>
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 RequestInfo(url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/service/g2/locate/execute.json'), method='GET', headers=<CIMultiDictProxy('Host': 'mobileapi.ca.prod.subarucs.com', 'User-Agent': 'Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.191030.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36', 'Origin': 'file://', 'X-Requested-With': 'ca.subaru.telematics.remote', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Cookie': 'JSESSIONID=C482925BE87D6E4DA1BEF2C99ADC8516; X-Oracle-BMC-LBS-Route=d21e0c9343d387ca18221aeed903afa1a7ab11a527da03a11a2ff120e313e9b656c62fd8a7c42ae81b8a6a868e2925dc0c84d9c0285f931c9c3be331')>, real_url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/service/g2/locate/execute.json'))
Error fetching subaru_data data: HTTP 504: <html>
 <head><title>504 Gateway Time-out</title></head>
 <body>
 <center><h1>504 Gateway Time-out</h1></center>
 <hr><center></center>
 </body>
 </html>
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 <!-- a padding to disable MSIE and Chrome friendly error page -->
 RequestInfo(url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/service/g2/condition/execute.json'), method='GET', headers=<CIMultiDictProxy('Host': 'mobileapi.ca.prod.subarucs.com', 'User-Agent': 'Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.191030.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36', 'Origin': 'file://', 'X-Requested-With': 'ca.subaru.telematics.remote', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Cookie': 'JSESSIONID=C482925BE87D6E4DA1BEF2C99ADC8516; X-Oracle-BMC-LBS-Route=d21e0c9343d387ca18221aeed903afa1a7ab11a527da03a11a2ff120e313e9b656c62fd8a7c42ae81b8a6a868e2925dc0c84d9c0285f931c9c3be331')>, real_url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/service/g2/condition/execute.json'))
Error fetching subaru_data data: HTTP 502: <html>
 <head><title>502 Bad Gateway</title></head>
 <body>
 <center><h1>502 Bad Gateway</h1></center>
 <hr><center></center>
 </body>
 </html>
 RequestInfo(url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/validateSession.json'), method='GET', headers=<CIMultiDictProxy('Host': 'mobileapi.ca.prod.subarucs.com', 'User-Agent': 'HomeAssistant/2026.5.4 aiohttp/3.13.5 Python/3.14', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Cookie': 'JSESSIONID=C482925BE87D6E4DA1BEF2C99ADC8516; X-Oracle-BMC-LBS-Route=d21e0c9343d387ca18221aeed903afa1a7ab11a527da03a11a2ff120e313e9b656c62fd8a7c42ae81b8a6a868e2925dc0c84d9c0285f931c9c3be331')>, real_url=URL('https://mobileapi.ca.prod.subarucs.com/g2v32/validateSession.json'))
```

**Comment by tweas** [comment]
I get the 504 error (and a 502 error) mixed in with the vehicle setup warnings I get (https://github.com/G-Two/homeassistant-subaru/issues/127)  Also causes a loss of functuionality until I reload the integration.  Possible that it is server side glitches on the subaru side?

2026-05-16 23:21:01.027 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-17 07:22:38.025 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-17 15:24:17.028 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-17 23:25:55.019 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-18 07:27:32.028 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-18 10:23:03.046 ERROR (MainThread) [homeassistant.components.github] An error occurred while processing new events - Server Error
2026-05-18 15:29:13.092 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-18 23:30:51.039 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-19 07:32:27.060 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-19 15:34:04.191 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-19 23:35:43.011 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-20 00:05:48.953 ERROR (MainThread) [custom_components.subaru] Error fetching subaru_data data: HTTP 502: <html>

2026-05-21 23:23:43.466 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-22 07:26:20.599 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-22 15:28:25.480 WARNING (MainThread) [subarulink.connection] VEHICLESETUPERROR received. Resetting session.
2026-05-22 19:39:10.539 ERROR (MainThread) [custom_components.subaru] Error fetching subaru_data data: HTTP 504: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center></center>
</body>
</html>
