### ISSUE TITLE
Configuration error - "Failed to set up"

### ISSUE THREAD

**Issue by noahkiss** [G-Two/homeassistant-subaru#132]
I recently updated to 0.7.15. The integration would work once, then I would have to reboot HA before it would work again. Now it shows as "Needs Attention - Failed to set up" - `AttributeError: 'Controller' object has no attribute 'has_lock_status'`. 

This error happens to also coincide with me adding a custom preset for climate control, which seems to be a new feature. Not sure if this is related or not so I'll add it here just in case.

2020 Forester. 

```
2024-12-04 17:18:45.934 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-04 17:18:45.938 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration config_editor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-04 17:18:45.940 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-04 17:18:45.943 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration subaru which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-04 17:19:54.629 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry [email] for subaru
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 102, in async_setup_entry
    vehicles[vin] = await _get_vehicle_info(controller, vin)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/subaru/__init__.py", line 207, in _get_vehicle_info
    VEHICLE_HAS_LOCK_STATUS: await controller.has_lock_status(vin),
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Controller' object has no attribute 'has_lock_status'
2024-12-04 17:19:57.602 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('synology_dsm', '74d4619ed9d8951cbff8a46bf89218d9'): 565163.942672484}
2024-12-05 05:05:00.552 ERROR (MainThread) [custom_components.pirateweather.weather_update_coordinator] Error requesting pirateweather data: 503, message='Service Unavailable', url='https://api.pirateweather.net/forecast/jI43Aldt2zmUeKj7vBk5kTSv90IDEhbJ/40.43850219281576,-78.39301202653844?units=si&extend=hourly&version=2'
2024-12-05 08:18:03.090 ERROR (MainThread) [homeassistant.components.script.start_car] Start Car: Choose at step 1: choice 1: Error executing script. Service not found for device at pos 1: Action select.select_option not found
2024-12-05 08:18:03.099 ERROR (MainThread) [homeassistant.components.script.start_car] Start Car: Error executing script. Service not found for choose at pos 1: Action select.select_option not found
2024-12-05 08:18:03.100 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall script.start_car (c:01JEBFGTRMAGPXWHNBKGE4TB7N)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/script/__init__.py", line 718, in _service_handler
    response = await self._async_start_run(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        variables=service.data, context=service.context, wait=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/script/__init__.py", line 674, in _async_start_run
    script_result = await coro
                    ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/script/__init__.py", line 707, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 1049, in _async_choose_step
    await self._async_run_script(script)
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 1274, in _async_run_script
    result = await self._async_run_long_action(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/script.py", line 781, in _async_device_step
    await device_action.async_call_action_from_config(
        self._hass, self._action, self._variables, self._context
    )
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/device_automation/action.py", line 72, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/select/device_action.py", line 122, in async_call_action_from_config
    await hass.services.async_call(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2735, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Action select.select_option not found
```

**Comment by G-Two** [comment]
Please attached the HA generated diagnostics output.

Does the preset selection feature work when starting the car with the provided button? Or does it only fail when using a script. If a script, please paste or attach the script yaml.

**Comment by noahkiss** [comment]
As far as I can tell, it just fails as soon as it's configured (added as a new entity in HA).

I do have a script which I use to call it, which worked fine previously:

```yaml
start_car:
  alias: Start Car
  sequence:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: weather.pirateweather
        attribute: temperature
        below: 50
      sequence:
      - device_id: 2db5272fc15bbdcc143edd57fe7959ec
        domain: select
        entity_id: select.VIN_climate_preset_2
        type: select_option
        option: Full Heat
      - device_id: 2db5272fc15bbdcc143edd57fe7959ec
        domain: button
        entity_id: button.VIN_remote_start
        type: press
    - conditions:
      - condition: numeric_state
        entity_id: weather.pirateweather
        attribute: temperature
        above: '73'
      sequence:
      - device_id: 2db5272fc15bbdcc143edd57fe7959ec
        domain: select
        entity_id: select.VIN_climate_preset_2
        type: select_option
        option: Full Cool
      - device_id: 2db5272fc15bbdcc143edd57fe7959ec
        domain: button
        entity_id: button.VIN_remote_start
        type: press
    default:
    - device_id: 2db5272fc15bbdcc143edd57fe7959ec
      domain: select
      entity_id: select.VIN_climate_preset_2
      type: select_option
      option: Auto
    - device_id: 2db5272fc15bbdcc143edd57fe7959ec
      domain: button
      entity_id: button.VIN_remote_start
      type: press
  mode: single
  icon: mdi:car
```

Here's how it looks:

<img width="1012" alt="Screenshot 2024-12-07 at 8 56 17 PM" src="https://github.com/user-attachments/assets/f88f10c6-5988-4a09-a090-cf998ee52a8c">

---

I'm not sure if this is the correct diagnostics - the actual car device doesn't seem to show up (maybe because it fails to register), but here is the diag file from the main HACS Subaru (or maybe everything it appears)

<details>
<summary>Diagnostics</summary>

```json
{
  "home_assistant": {
    "installation_type": "Unsupported Third Party Container",
    "version": "2024.12.0",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.13.0",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "4.4.302+",
    "run_as_root": false
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "config_editor": {
      "documentation": "https://github.com/junkfix/config-editor-card",
      "version": "4.4.2",
      "requirements": []
    },
    "pirateweather": {
      "documentation": "https://github.com/alexander0042/pirate-weather-ha",
      "version": "1.6.3",
      "requirements": []
    },
    "subaru": {
      "documentation": "https://github.com/G-Two/homeassistant-subaru",
      "version": "0.7.15",
      "requirements": [
        "subarulink==0.7.12"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "after_dependencies": [
      "python_script"
    ],
    "codeowners": [
      "ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "2.0.1",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 4.751596134155989e-05
    },
    "3b9d1af7729c84f094d88175c5d539d0": {
      "wait_import_platforms": -0.8019394959555939,
      "wait_base_component": -0.0014418850187212229,
      "config_entry_setup": 1.3106917570112273
    }
  },
  "data": {
    "entry": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "token": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "hacs",
      "entry_id": "3b9d1af7729c84f094d88175c5d539d0",
      "minor_version": 1,
      "modified_at": "1970-01-01T00:00:00+00:00",
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "",
      "unique_id": null,
      "version": 1
    },
    "hacs": {
      "stage": "running",
      "version": "2.0.1",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "template",
        "theme",
        "plugin",
        "integration"
      ],
      "renamed_repositories": {
        "PepegaBruh/CryptoTracker": "BigNocciolino/CryptoTracker",
        "9a4gl/hass-peltec": "9a4gl/hass-centrometal-boiler",
        "nbogojevic/homeassistant-midea-dehumidifier-lan": "nbogojevic/homeassistant-midea-air-appliances-lan",
        "78wesley/Darkish-Theme": "78wesley/Home-Assistant-Darkish-Theme",
        "KartoffelToby/ai_thermostat": "KartoffelToby/better_thermostat",
        "nikrolls/homeassistant-goldair-climate": "nicole-ashley/homeassistant-goldair-climate",
        "wills106/homsassistant-solax-modbus": "wills106/homeassistant-solax-modbus",
        "dmitry-k/yandex_smart_home": "dext0r/yandex_smart_home",
        "uvjustin/alarmdotcom": "pyalarmdotcom/alarmdotcom",
        "wernerhp/ha_integration_load_shedding": "wernerhp/ha.integration.load_shedding",
        "TheLastProject/lovelace-valetudo-map-card": "Hypfer/lovelace-valetudo-map-card",
        "fuatakgun/kia_uvo": "Hyundai-Kia-Connect/kia_uvo",
        "jadson179/consul": "gtjadsonsantos/consul",
        "Farfar/homeassistant-skodaconnect": "skodaconnect/homeassistant-skodaconnect",
        "lendy007/homeassistant-skodaconnect": "skodaconnect/homeassistant-skodaconnect",
        "rowysock/home-assistant-HomeWhiz": "home-assistant-HomeWhiz/home-assistant-HomeWhiz",
        "Wibias/hass-variables": "enkama/hass-variables",
        "jvitkauskas/homeassistant_salus": "epoplavskis/homeassistant_salus",
        "custom-components/alexa_media_player": "alandtse/alexa_media_player",
        "johanfrick/custom-sonos-card": "punxaphil/custom-sonos-card",
        "arjenvrh/audi_connect_ha": "audiconnect/audi_connect_ha",
        "htmltiger/config-editor-card": "junkfix/config-editor-card",
        "htmltiger/numberbox-card": "junkfix/numberbox-card",
        "htmltiger/config-editor": "junkfix/config-editor",
        "orickcorreia/caule-themes-pack-1": "ricardoquecria/caule-themes-pack-1",
        "jonasniesner/open_epaper_link_homeassistant": "OpenEPaperLink/Home_Assistant_Integration",
        "Limych/ha-temperature-feels-like": "Limych/ha-apparent-temperature",
        "wimb0/home-assistant-saj-modbus": "wimb0/home-assistant-saj-r5-modbus",
        "t0mer/ims-custom-component": "GuyKh/ims-custom-component",
        "jm-73/Indego": "sander1988/Indego"
      },
      "archived_repositories": [
        "pfunkmallone/HACS-camect-integration",
        "Raukze/home-assistant-fitx",
        "echoromeo/hanobo",
        "spycle/microbot_push",
        "DSorlov/hasl-platform",
        "rccoleman/lamarzocco",
        "JuanMTech/orange_dark",
        "pfunkmallone/HACS-camect-custom_card",
        "ThomasPrior/FlexpoolInfo",
        "gerardag/person-entity-card",
        "custom-cards/text-element",
        "Sholofly/arrisdcx960",
        "patrickhilker/tedee_hass_integration",
        "custom-components/sensor.untappd",
        "a529987659852/openwbmqtt",
        "custom-cards/upcoming-media-card",
        "JuanMTech/green_light_mode",
        "ThomasPrior/EthermineInfo",
        "robmarkcole/HASS-Deepstack-face",
        "briis/hass-weatherflow",
        "Tiemooowh/homeassistant-teletask",
        "custom-components/sensor.radarr_upcoming_media",
        "daenny/climate_group",
        "clayauld/lovelace-darksky-card",
        "disforw/inverse",
        "dr1rrb/ha-twinkly",
        "gjohansson-ST/stl",
        "robmarkcole/HASS-Deepstack-object",
        "codyc1515/ha-contact-energy",
        "DCSBL/ha-homewizard-energy",
        "custom-components/unsplash",
        "maykar/lovelace-swipe-navigation",
        "Kraineff/philips-airpurifier",
        "digitaljamie/google-theme",
        "Mr-Groch/HA-Emulated-Color-Temp-Light",
        "speleolontra/daikin_residential_altherma",
        "ppanagiotis/pymusiccast",
        "maykar/plex_assistant",
        "maykar/kiosk-mode",
        "eavanvalkenburg/sia",
        "pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer",
        "NemesisRE/lovelace-swipe-navigation",
        "thebino/rki_covid",
        "custom-components/sensor.plex_recently_added",
        "bieniu/ha-zadnego-ale",
        "walthowd/ha-automower",
        "custom-components/wienerlinien",
        "frenck/home-assistant-theme-outline",
        "JuanMTech/green_dark_mode",
        "Cyr-ius/hass-cozytouch",
        "alexarch21/history-explorer-card",
        "custom-cards/ext-weblink",
        "iantrich/aftership-card",
        "JuanMTech/orange_light",
        "custom-cards/state-element",
        "Thomas55555/husqvarna_automower",
        "sakowicz/home-assistant-tenda-tracker",
        "custom-components/templatesensor",
        "GeorgeSG/lovelace-folder-card",
        "jessevl/homeassistant-greenchoice",
        "ryanwinter/hass-rainforest-emu-2",
        "tikismoke/home-assistant-nespressoble",
        "custom-components/sensor.sonarr_upcoming_media",
        "custom-components/breaking_changes",
        "Cyr-ius/hass-hue-service-advanced",
        "DavidMStraub/homeassistant-homeconnect",
        "chaptergy/noctis-grey",
        "custom-cards/state-attribute-element",
        "estevez-dev/extended-banner-card",
        "cgarwood/homeassistant-fullykiosk",
        "marrobHD/firetv-card",
        "nagyrobi/home-assistant-custom-components-cover-rf-time-based",
        "dynasticorpheus/gigasetelements-ha",
        "custom-cards/username-element",
        "dgomes/ha_rrd_recorder",
        "KTibow/lovelace-dark-soft-ui-theme",
        "lukich48/hass_mqtt_template_switch",
        "marcomow/ble-bulb-card",
        "natekspencer/hacs-litterrobot",
        "custom-cards/favicon-counter",
        "nagyrobi/home-assistant-custom-components-pfsense-gateways",
        "custom-components/authenticated",
        "custom-components/sensor.yandex_maps",
        "KTibow/lovelace-light-soft-ui-theme",
        "ljmerza/ha-our-groceries",
        "DeebotUniverse/Deebot-4-Home-Assistant",
        "AitorDB/home-assistant-sun-card",
        "georgezhao2010/climate_ewelink",
        "TheLastProject/lovelace-media-art-background",
        "heinoldenhuis/home_assistant_omnik_solar",
        "JuanMTech/amoled_blue",
        "hacf-fr/hassRenaultZE",
        "custom-components/combined",
        "custom-components/config_check"
      ],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [
      "G-Two/homeassistant-subaru"
    ],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "config_flow": false,
          "default_branch": null,
          "description": "Home Assistant Configuration Files Editor for Lovelace",
          "domain": "",
          "downloads": 0,
          "etag_repository": "W/\"d1faf928a4968dc4d05241227b71193edb8f85dedbbb116d85bc9ea6f54f7c56\"",
          "etag_releases": null,
          "file_name": null,
          "first_install": false,
          "full_name": "junkfix/config-editor-card",
          "hide": false,
          "has_issues": true,
          "id": "433577603",
          "installed_commit": "b881e60",
          "installed_version": "4.7",
          "installed": true,
          "last_commit": "b881e60",
          "last_updated": "2024-04-09T16:14:55Z",
          "last_version": "4.7",
          "manifest_name": null,
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 78,
          "topics": [
            "homeassistant-addons",
            "homeassistant-config",
            "homeassistant-configuration",
            "yaml"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "config-editor-card.js",
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Config Editor Card",
            "filename": "config-editor-card.js",
            "render_readme": true
          },
          "name": "Config Editor Card",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/www/community/config-editor-card",
          "local": "/config/www/community/config-editor-card",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@junkfix"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "Home Assistant Configuration Editor Helper",
          "domain": "config_editor",
          "downloads": 0,
          "etag_repository": "W/\"83823e26bb8084e52c0455f09aca8693e77ec11f2d17fb23214c1bf81696dd8d\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "junkfix/config-editor",
          "hide": false,
          "has_issues": true,
          "id": "433577406",
          "installed_commit": "0baa420",
          "installed_version": "4.4.2",
          "installed": true,
          "last_commit": "0baa420",
          "last_updated": "2024-09-03T23:55:18Z",
          "last_version": "4.4.2",
          "manifest_name": "Config Editor",
          "new": false,
          "open_issues": 0,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 40,
          "topics": [
            "homeassistant-config"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": null,
          "manifest": {
            "name": "Config Editor",
            "render_readme": true
          },
          "name": "Config Editor",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/config_editor",
          "local": "/config/custom_components/config_editor",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@G-Two"
          ],
          "category": "integration",
          "config_flow": true,
          "default_branch": "main",
          "description": "Subaru STARLINK custom component for Home Assistant.",
          "domain": "subaru",
          "downloads": 0,
          "etag_repository": "W/\"d36a35ba0865b7492a4ae405b96a5b491256b99dca78c9d542db0a846a574fc9\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "G-Two/homeassistant-subaru",
          "hide": false,
          "has_issues": true,
          "id": "316604385",
          "installed_commit": "b47f61a",
          "installed_version": "v0.7.15",
          "installed": true,
          "last_commit": "73cec62",
          "last_updated": "2024-12-08T01:01:32Z",
          "last_version": "v0.7.15",
          "manifest_name": "Subaru (HACS)",
          "new": false,
          "open_issues": 13,
          "prerelease": "v0.7.16rc2",
          "published_tags": [
            "v0.7.15",
            "v0.7.14",
            "v0.7.13",
            "v0.7.12",
            "v0.7.11",
            "v0.7.10",
            "v0.7.9",
            "v0.7.8",
            "v0.7.7",
            "v0.7.6",
            "v0.7.5",
            "v0.7.4",
            "v0.7.3",
            "v0.7.2",
            "v0.7.1",
            "v0.7.0",
            "v0.6.5",
            "v0.6.4",
            "v0.6.3",
            "v0.6.2",
            "v0.6.1",
            "v0.6.0",
            "v0.5.2",
            "v0.5.1",
            "v0.5.0",
            "v0.4.2",
            "v0.4.1"
          ],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 56,
          "topics": [
            "subaru"
          ]
        },
        "integration_manifest": {
          "domain": "subaru",
          "name": "Subaru (HACS)",
          "codeowners": [
            "@G-Two"
          ],
          "config_flow": true,
          "documentation": "https://github.com/G-Two/homeassistant-subaru",
          "iot_class": "cloud_polling",
          "issue_tracker": "https://github.com/G-Two/homeassistant-subaru/issues",
          "requirements": [
            "subarulink==0.7.12"
          ],
          "version": "0.7.15"
        },
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2022.10",
          "manifest": {
            "name": "Subaru (HACS)",
            "render_readme": true,
            "homeassistant": "2022.10"
          },
          "name": "Subaru (HACS)",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": "v0.7.15",
        "paths": {
          "localpath": "/config/custom_components/subaru",
          "local": "/config/custom_components/subaru",
          "remote": "custom_components/subaru"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 634749,
          "etag_repository": "W/\"82211988dd05c64c626ff8cf8e12db48082fb791e59dfb58fa0574c4cd29b069\"",
          "etag_releases": "W/\"87803edce4eb4add56c9045038599fa711435494e8b4c5d1935740b7880558d0\"",
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": "aeb2a44",
          "installed_version": "2.0.1",
          "installed": true,
          "last_commit": "b0b4188",
          "last_updated": "2024-12-06T13:58:18Z",
          "last_version": "2.0.1",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 40,
          "prerelease": null,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 5503,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2024.4.1",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2024.4.1",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@alexander0042"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "Replacement for the default Dark Sky Home Assistant integration using Pirate Weather ",
          "domain": "pirateweather",
          "downloads": 8,
          "etag_repository": "W/\"96a5dbb0997cc21e10d98b9a6b8c1c599d8a416c0601d24bf1c66d115c58353b\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "Pirate-Weather/pirate-weather-ha",
          "hide": false,
          "has_issues": true,
          "id": "366713850",
          "installed_commit": "3dd952a",
          "installed_version": "v1.6.3",
          "installed": true,
          "last_commit": "4d2f6fd",
          "last_updated": "2024-12-02T19:29:23Z",
          "last_version": "v1.6.3",
          "manifest_name": "Pirate Weather",
          "new": false,
          "open_issues": 0,
          "prerelease": "v1.6.3-dev",
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 369,
          "topics": [
            "darksky-api",
            "weather-api"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": null,
          "hacs": null,
          "hide_default_branch": false,
          "homeassistant": "2023.10.0",
          "manifest": {
            "name": "Pirate Weather",
            "render_readme": true,
            "homeassistant": "2023.10.0"
          },
          "name": "Pirate Weather",
          "persistent_directory": null,
          "render_readme": true,
          "zip_release": false
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/pirateweather",
          "local": "/config/custom_components/pirateweather",
          "remote": "custom_components"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 6,
          "remaining": 4994,
          "reset": 1733626636
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1733623478
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1733627018
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1733627018
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1733623478
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1733627018
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1733627018
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1733627018
        },
        "dependency_snapshots": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1733623478
        }
      },
      "rate": {
        "limit": 5000,
        "used": 6,
        "remaining": 4994,
        "reset": 1733626636
      }
    }
  }
}
```

</details>

**Comment by G-Two** [comment]
I reverted my setup to 0.7.15 but was unable to duplicate this issue on my end. The specific error message `AttributeError: 'Controller' object has no attribute 'has_lock_status'` might be caused if the updated subarulink package dependency required for 0.7.15 was never installed. Try updating to the latest pre-release 0.7.16rc2 since that will force a package upgrade.

**Comment by noahkiss** [comment]
that must have been it - as soon as I went to rc2, the issue seemed to clear itself up. My script ran successfully as well after updating to refresh the climate options. Thanks for the suggestion and continued development! 

<details>
<summary>Updated script for anyone referencing this</summary>

I trigger this script using my iPhone by creating a homekit bridge integration which is configured to run the script and shows up as a script in my Home app. This was built with the visual editor in HA, screenshot below the script.

```yaml
alias: Start Car
sequence:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: weather.pirateweather
            attribute: temperature
            below: 50
        sequence:
          - device_id: 2db5272fc15bbdcc143dff57fe7959ec
            domain: select
            entity_id: f4c69eacf294712cb4a0496c8200d86f
            type: select_option
            option: Heat
          - device_id: 2db5272fc15bbdcc143dff57fe7959ec
            domain: button
            entity_id: button.jf2skajc0lh465144_remote_start
            type: press
      - conditions:
          - condition: numeric_state
            entity_id: weather.pirateweather
            attribute: temperature
            above: "73"
        sequence:
          - device_id: 2db5272fc15bbdcc143dff57fe7959ec
            domain: select
            entity_id: f4c69eacf294712cb4a0496c8200d86f
            type: select_option
            option: Full Cool
          - device_id: 2db5272fc15bbdcc143dff57fe7959ec
            domain: button
            entity_id: button.jf2skajc0lh465144_remote_start
            type: press
    default:
      - device_id: 2db5272fc15bbdcc143dff57fe7959ec
        domain: select
        entity_id: f4c69eacf294712cb4a0496c8200d86f
        type: select_option
        option: Auto
      - device_id: 2db5272fc15bbdcc143dff57fe7959ec
        domain: button
        entity_id: button.jf2skajc0lh465144_remote_start
        type: press
mode: single
icon: mdi:car
```
<img width="1012" alt="Screenshot 2024-12-07 at 8 56 17 PM" src="https://github.com/user-attachments/assets/c4cb4d95-fb86-4ada-8a6f-75f3e1946394">



</details>
