### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by khrisperry** [G-Two/homeassistant-subaru#74]
Hi All, so everytime I try to upgrade the software from HACS, I get the following error and have to roll back to the previous version I was on.  Can anyone help with this?

 subaru
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/subaru/__init__.py", line 102, in async_setup_entry
    vehicles[vin] = _get_vehicle_info(controller, vin)
  File "/config/custom_components/subaru/__init__.py", line 220, in _get_vehicle_info
    VEHICLE_API_GEN: controller.get_api_gen(vin),
  File "/usr/local/lib/python3.10/site-packages/subarulink/controller.py", line 362, in get_api_gen
    _LOGGER.debug("Getting vehicle API gen %s:%s", vin, result)
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by G-Two** [comment]
0.7.4 should fix that particular bug, although I'm curious as to why the subaru API is not reporting an API generation for this vehicle (the expected value of `result` in the traceback pasted above). Do you have an older vehicle on your account that doesn't have a starlink subscription?

**Comment by khrisperry** [comment]
Thank you!  Best news I've got all day on a fix for this.  And yes, I have 2 vehicles on my account.  My 2019 WRX does not have a starlink subscription, but my 2020 Ascent does have the subscription.  Hopefully that helps!
